# NOTE: it's a wireguard client config file, used to connect to the wireguard server
# WARN: import configuration from the WG server
[Interface]
Address = 10.8.1.1/32
DNS = 127.0.0.1, 1.0.0.1
PrivateKey = *******
Jc = 42
Jmin = 42
Jmax = 42
S1 = 42
S2 = 42
S3 = 42
S4 = 42
H1 = 42-142
H2 = 42-142
H3 = 42-142
H4 = 42-142
I1 = xyz
# I3 = 
# I4 = 
# I5 = 

[Peer]
PublicKey = xyz
PresharedKey = xyz
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 127.0.0.1:12345
PersistentKeepalive = 42
